// FILE GENERATED BY: flutterfire configure
//
// To regenerate this file with real values:
//
//   Step 1 – Log in to Firebase (one-time, requires your Google account):
//     firebase login
//
//   Step 2 – Create a Firebase project at https://console.firebase.google.com
//             and enable Cloud Firestore (in Native mode).
//
//   Step 3 – Run FlutterFire configure from this project folder:
//     cd smart_class_app
//     flutterfire configure
//             Select your project when prompted, and pick android + web at minimum.
//             This command replaces this file with real API keys.
//
// Until then, the app starts normally but Firestore writes are silently skipped.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
      case TargetPlatform.windows:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions: run "flutterfire configure" to generate '
          'real options for this platform.',
        );
    }
  }

  // ── Replace everything below with the output of "flutterfire configure" ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSPQYFEUnagQyHZRj1k9zOiT1pIMpKb_g',
    appId: '1:1045441834269:web:8f127906a09c009658c5f4',
    messagingSenderId: '1045441834269',
    projectId: 'smartclass-e607d',
    authDomain: 'smartclass-e607d.firebaseapp.com',
    storageBucket: 'smartclass-e607d.firebasestorage.app',
    measurementId: 'G-QZ9WMNCC91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATF29k2P5auGKc_9o_vy_SihSRRRnRCY',
    appId: '1:1045441834269:android:58f7e39644f7666758c5f4',
    messagingSenderId: '1045441834269',
    projectId: 'smartclass-e607d',
    storageBucket: 'smartclass-e607d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4deEgbYruBWSNwao5Jy55lrJwOLaMSc',
    appId: '1:1045441834269:ios:4903f66917cb50c058c5f4',
    messagingSenderId: '1045441834269',
    projectId: 'smartclass-e607d',
    storageBucket: 'smartclass-e607d.firebasestorage.app',
    iosBundleId: 'com.example.smartClassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: 'REPLACE_WITH_REAL_APP_ID',
    messagingSenderId: 'REPLACE',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.smartClassApp',
  );
}